server:
  # TO ALLOW SPRING BOOT TO RANDOMLY PICK ANY AVAILABLE PORT WHILE RUNNING
  port: 0

spring:
  application:
    name: RECOMMENDATION-SERVICE
  # =====================================
  # Elasticsearch Configurations
  # =====================================
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9200
      repositories:
        enabled: true

# ========================================
# Eureka Service Discovery configurations
# ========================================
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
