server:
  # TO ALLOW SPRING BOOT TO RANDOMLY PICK ANY AVAILABLE PORT WHILE RUNNING
  port: 0

spring:
  application:
    name: AUTH-SERVICE
  # =====================================
  # MYSQL Configurations
  # =====================================
  datasource:
    url: jdbc:mysql://localhost:3306/wms-auth
    username: root
    password: Shrangika@13
    driver-class-name: com.mysql.cj.jdbc.Driver

  # =====================================
  # JPA Configurations
  # =====================================
  jpa:
    #    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    serialization:
      write_dates_as_timestamps: false

  # ========================================
  # Email configurations
  # ========================================
  mail:
    host: smtp.gmail.com
    port: 465
    username: connectitlabs@gmail.com
    password: ozdyvwabsdqawera
    protocol: smtp
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory

# ========================================
# Eureka Service Discovery configurations
# ========================================
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
