version: '3.3'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass redis-password
    volumes:
      - /data/redis/data:/root/redis
  mysql:
    image: mysql:8.0
    volumes:
      - wms-data:/var/lib/mysql
      - ./db-init-setup.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
volumes:
  wms-data:
