version: '3.3'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass redis-password
    volumes:
      - /data/redis/data:/root/redis
  mysql:
    image: mysql:8.0
    volumes:
      - wms-data:/var/lib/mysql
      - ./db-init-setup.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
  elasticsearch:
    image: elasticsearch:8.12.1
    environment:
      - SYSCTL_CAP_NET_ADMIN=1
      - VM_MAX_MAP_COUNT=262144
      - "ES_JAVA_OPTS=-Xms1500m -Xmx1500m"
      - discovery.type=single-node
      - bootstrap.memory_lock=false
    mem_limit: 2g
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
volumes:
  wms-data:
  elasticsearch-data:
