server:
  port: 8761

spring:
  application:
    name: DISCOVERY-SERVER
  security:
    user:
      name: eureka
      password: password

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false

