server:
  # TO ALLOW SPRING BOOT TO RANDOMLY PICK ANY AVAILABLE PORT WHILE RUNNING
  port: 0

spring:
  application:
    name: EMPLOYEES-SERVICE
  # =====================================
  # MYSQL Configurations
  # =====================================
  datasource:
    url: jdbc:mysql://localhost:3306/wms-employees
    username: root
    password: Shrangika@13
    driver-class-name: com.mysql.cj.jdbc.Driver

  # =====================================
  # JPA Configurations
  # =====================================
  jpa:
    #    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    serialization:
      write_dates_as_timestamps: false

# ========================================
# Eureka Service Discovery configurations
# ========================================
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
